name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  postgresql2: ^1.0.4
  redis: ^3.1.0
  result_dart: ^1.1.0
  shelf: ^1.4.1
  shelf_modular: ^2.1.0
  uno: ^1.1.1
  # path: ^1.8.0

dev_dependencies:
  flutterando_analysis: ^0.0.2
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0
